function writeHeadNav() {

document.write('<header>');document.write('	<div id="leagueLogo">');document.write('		<img src="images/alooo_logo.jpg" alt="A LEAGUE OF OUR OWN">');document.write('	</div>');document.write('	<div id="teamLogos">');
document.write('		<img src="images/orange_black_hat_100.gif" title="Conquistadors">');document.write('		<img src="images/camels_192.jpg" title="Cuban Camels">');
document.write('		<img src="images/decimators_90.jpg" title="Dwarven Decimators">');document.write('		<img src="images/green_black_hat_100.gif" title="Isotopes">');document.write('		<img src="images/red_jersey_100.gif" title="Jackie Treehorn">');document.write('		<img src="images/blue_black_hat_100.gif" title="Life With Fernandez">');document.write('		<img src="images/lnt_v2_100.png" title="Lightning N Thunder">');
document.write('		<img src="images/mrobz_v3_100.png" title="Mookies">');
document.write('		<img src="images/possums_192.jpg" title="Pissed Off Possums">');document.write('		<img src="images/sultans_v2_192.jpg" title="Sultans of Dallas">');document.write('		<img src="images/red_hat_100.gif" title="Three Finger'+"'"+'s Ghost">');document.write('		<img src="images/blue_black_hat_100.gif" title="Washington McNasty">');document.write('	</div>');document.write('</header>');document.write('<nav>');
document.write('	<a class="menuButton" href="javascript:toggleMainNavVis()">');
document.write('		<svg>');
document.write('			<rect x="0" y="0" height="10px" width="45px" />');
document.write('			<rect x="0" y="18" height="10px" width="45px" />');
document.write('			<rect x="0" y="36" height="10px" width="45px" />');
document.write('		</svg>');
document.write('	</a>');document.write('	<div class="navItem">');document.write('		<a href="index.html">Home</a>');document.write('	</div>');document.write('	<div class="navItem">');document.write('		<a href="javascript:toggleSubNav('+"'"+'history'+"'"+')">History</a>');document.write('		<div class="subNav mobile-down" id="history" style="visibility:hidden" onmouseleave="closeSubNav('+"'"+'history'+"'"+')">');document.write('			<span>History</span>');document.write('			<a>Standings</a>');document.write('			<a href="awards_history.html">Awards</a>');document.write('			<a>Franchise</a>');document.write('			<a>Ownership</a>');
document.write('			<a>Voting</a>');document.write('		</div>');document.write('	</div>');document.write('	<div class="navItem">');document.write('		<a>Rules</a>');document.write('	</div>');
document.write('	<div class="navItem">');
document.write('		<a>Podcast</a>');
document.write('	</div>');document.write('	<div class="navItem">');document.write('		<a href="javascript:toggleSubNav('+"'"+'roto'+"'"+')">Roto Standings</a>');document.write('		<div class="subNav" id="roto" style="visibility:hidden" onmouseleave="closeSubNav('+"'"+'roto'+"'"+')">');document.write('			<span>Roto&nbsp;Standings</span>');document.write('			<a>2009</a>');document.write('			<a>2010</a>');document.write('			<a>2011</a>');document.write('			<a>2012</a>');document.write('			<a>2013</a>');document.write('			<a>2014</a>');
document.write('			<a href="roto15.html">2015</a>');document.write('		</div>');document.write('	</div>');
document.write('	<div class="navItem">');
document.write('		<a>Salary Planner</a>');
document.write('	</div>');document.write('	<div class="navItem">');document.write('		<a href="javascript:toggleSubNav('+"'"+'keepers'+"'"+')">Keepers</a>');document.write('		<div class="subNav" id="keepers" style="visibility:hidden" onmouseleave="closeSubNav('+"'"+'keepers'+"'"+')">');document.write('			<span>Keepers</span>');document.write('			<a>2010</a>');
document.write('			<a>2009</a>');
document.write('			<a>2010</a>');
document.write('			<a>2011</a>');
document.write('			<a>2012</a>');
document.write('			<a>2013</a>');
document.write('			<a>2014</a>');
document.write('			<a>2015</a>');document.write('		</div>');document.write('	</div>');document.write('	<div class="navItem">');document.write('		<a href="javascript:toggleSubNav('+"'"+'draft'+"'"+')">Draft Results</a>');document.write('		<div class="subNav" id="draft" style="visibility:hidden" onmouseleave="closeSubNav('+"'"+'draft'+"'"+')">');document.write('			<span>Draft&nbsp;Results</span>');
document.write('			<a>2009</a>');
document.write('			<a>2010</a>');
document.write('			<a>2011</a>');
document.write('			<a>2012</a>');
document.write('			<a>2013</a>');
document.write('			<a>2014</a>');
document.write('			<a>2015</a>');document.write('		</div>');document.write('	</div>');document.write('	<div class="navItem">');document.write('		<a href="javascript:toggleSubNav('+"'"+'rosters'+"'"+')">Off-Season Rosters</a>');document.write('		<div class="subNav" id="rosters" style="visibility:hidden" onmouseleave="closeSubNav('+"'"+'rosters'+"'"+')">');document.write('			<span>Off-Season&nbsp;Rosters</span>');
document.write('			<a>2009</a>');
document.write('			<a>2010</a>');
document.write('			<a>2011</a>');
document.write('			<a>2012</a>');
document.write('			<a>2013</a>');
document.write('			<a>2014</a>');
document.write('			<a>2015</a>');document.write('		</div>');document.write('	</div>');
document.write('	<div class="navItem">');
document.write('		<a href="javascript:toggleSubNav('+"'"+'expansion'+"'"+')">Expansion</a>');
document.write('		<div class="subNav" id="expansion" style="visibility:hidden" onmouseleave="closeSubNav('+"'"+'expansion'+"'"+')">');
document.write('			<span>Expansion</span>');
document.write('			<a>2015&nbsp;Draft&nbsp;Results</a>');
document.write('			<a>2015&nbsp;Protected&nbsp;Players</a>');
document.write('			<a>2015&nbsp;Expansion&nbsp;"Sandbox"</a>');
document.write('		</div>');
document.write('	</div>');document.write('</nav>');

}